### ISSUE TITLE
Error: Undefined variable: user

### ISSUE THREAD

**Issue by refgd** [PaulLereverend/NextcloudVideo_Converter#35] opened 2020-03-20 19:13 UTC
Undefined variable: user at .../apps/video_converter/lib/Controller/ConversionController.php#44

**Comment by halleknast** [comment] 2020-03-23 11:22
Seems to be caused by f0622e043255ff0eaf9e968307bfe3a7591c3f0c. Not really sure what that commit was for, it looks like a mistake to me.

**Comment by PaulLereverend** [comment] 2020-04-19 13:34
Fixed in 229bc7a (latest update). Can you confirm ?

**Comment by halleknast** [comment] 2020-04-19 13:53
Yes - thanks!

**Closed** 2020-04-19 14:14 UTC
